TP-NT-Taller-Meacanico/TP-NT-Taller-Meacanico/Models/Autopart.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TP_NT_Taller_Meacanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Autopart
    {
        public Autopart()
        {
            this.Order_Autopart = new HashSet<Order_Autopart>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
    
        public virtual ICollection<Order_Autopart> Order_Autopart { get; set; }
    }
}

TP-NT-Taller-Meacanico/TP-NT-Taller-Meacanico/Controllers/AutopartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TP_NT_Taller_Meacanico.Models;

namespace TP_NT_Taller_Meacanico.Controllers
{
    public class AutopartController : Controller
    {
        private DBWrapper dbWrapper = new DBWrapper();

        [HttpGet]
        public ActionResult AutoPartEdit(int orderID)
        {
            List<AutoPartsOrderWrapper> aoList = dbWrapper.GetAllAutopartsByOrderID(orderID);

            var model = new AutopartsOrderInfo
            {
                orderID = orderID,
                apo = aoList
            };

            return View(model);
        }

        [HttpGet]
        public ActionResult AutopartForm(int orderID)
        {
            List<Autopart> autoparts = dbWrapper.GetAllAutoparts();

            var model = new AutopartsOrderInfo
            {
                orderID = orderID,
                autoparts = autoparts
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult AutopartAdd(int orderID, int autopartID, int hours, int quantity)
        {
            Order_Autopart oa = new Order_Autopart
            {
                order_id = orderID,
                autopart_id = autopartID,
                hours = hours,
                quantity = quantity
            };

            dbWrapper.AddAutoPartOrder(oa);

            return RedirectToAction("AutoPartEdit", new { orderID = orderID });
        }
    }
}

TP-NT-Taller-Meacanico/TP-NT-Taller-Meacanico/Views/Autopart/AutoPartEdit.cshtml
@model TP_NT_Taller_Meacanico.Models.AutopartsOrderInfo

@{
    ViewBag.Title = "AutoPartEdit";
}

<h2>Detailed list of autoparts for order #@Model.orderID</h2>
<div class="container">
    <h2>Orders</h2>
    @if (Model.apo != null)
    {
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Price per unit</th>
                    <th>Hours</th>
                    <th>Quantity</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var ao in Model.apo)
                {
                    <tr>
                        <td>@ao.name</td>
                        <td>$@ao.price</td>
                        <td>@ao.hours</td>
                        <td>@ao.quantity</td>
                    </tr>
                }
            </tbody>
        </table>
    }
    else
    {
        <h3>No autoparts found</h3>
    }
</div>

<button type="button" class="btn btn-default btn-sm" style="margin-left: 15px;">
    <a href="AutopartForm?orderID=@Model.orderID">
        Add Autopart
    </a>
</button>

TP-NT-Taller-Meacanico/TP-NT-Taller-Meacanico/Views/Autopart/AutopartForm.cshtml
@model TP_NT_Taller_Meacanico.Models.AutopartsOrderInfo

@{
    ViewBag.Title = "AutopartForm";
}

<h2>AutopartForm</h2>

@using (Html.BeginForm("AutopartAdd", "Autopart"))
{
    <div class="container">
        <form>
            <div class="form-group">
                <label for="autopartID">Autoparts' list (select one):</label>
                <select class="form-control" id="autopartID" name="autopartID">
                    <option>Select autopart</option>
                    @foreach (var autopart in Model.autoparts)
                    {
                        <option value="@autopart.id">@autopart.name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label for="quantity">Quantity:</label>
                <input type="text" class="form-control" id="quantity" placeholder="Enter a quantity" name="quantity">
            </div>
            <div class="form-group">
                <label for="hours">Hours spent:</label>
                <input type="text" class="form-control" id="hours" placeholder="Enter hours' quantity" name="hours">
            </div>
            <div class="form-group" style="visibility: hidden">
                <label for="orderID">Order ID:</label>
                <input type="text" class="form-control" id="orderID" name="orderID" value="@Model.orderID">
            </div>
            <button type="submit" class="btn btn-default" style="margin-top: -130px;">Submit</button>
        </form>
    </div>
}
<br />

<button type="button" class="btn btn-default btn-sm" style="margin-left: 15px;">
    <a href="AutopartEdit?orderID=@Model.orderID">
        Return
    </a>
</button>